# Generated by Django 5.0.4 on 2024-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('roll', models.IntegerField()),
                ('mobile_number', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('passed', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('birth_date', models.DateField()),
                ('class_length', models.DurationField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
